### ISSUE TITLE
Process Guru Chronicles Book with Anchor in Every Paragraph

### ISSUE THREAD

**Issue by Brahmanathaswami** [soapdog/hap-epub-export-tool#3]

**Comment by soapdog** [comment]
Processed [The Guru Chronicles](http://dev.himalayanacademy.com/media/books/the-guru-chronicles/web/). You may need to reload twice to update the cache with the new version. 

Next to each paragraph there is a paragraph symbol which can be used to get a link to that paragraph. 

![the guru chronicles - firefox nightly 2018-12-12 13 42 29](https://user-images.githubusercontent.com/23247/49873481-e2efcc00-fe13-11e8-8c3d-ec5e30c85691.png)

Opening that link causes the page to open and focus on that paragraph.

![the guru chronicles - firefox nightly 2018-12-12 13 43 51](https://user-images.githubusercontent.com/23247/49873522-fc911380-fe13-11e8-8b40-282804930d2b.png)
